// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// soft_c
double soft_c(double a, double lambda);
RcppExport SEXP _MicrobiomeStat_soft_c(SEXP aSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(soft_c(a, lambda));
    return rcpp_result_gen;
END_RCPP
}
// ADMM_ab_cpp
Rcpp::List ADMM_ab_cpp(NumericVector C, NumericVector lambda, double mu, int maxit, double eps);
RcppExport SEXP _MicrobiomeStat_ADMM_ab_cpp(SEXP CSEXP, SEXP lambdaSEXP, SEXP muSEXP, SEXP maxitSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ADMM_ab_cpp(C, lambda, mu, maxit, eps));
    return rcpp_result_gen;
END_RCPP
}
// Soft_threshold_cpp
Rcpp::List Soft_threshold_cpp(NumericVector C, NumericVector lambda);
RcppExport SEXP _MicrobiomeStat_Soft_threshold_cpp(SEXP CSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(Soft_threshold_cpp(C, lambda));
    return rcpp_result_gen;
END_RCPP
}
// bmdd_nlopt
List bmdd_nlopt(NumericMatrix W, String type, Nullable<NumericVector> para_alp_init, Nullable<NumericVector> para_pi_init, Nullable<NumericMatrix> gam_init, int iterlim, double tol, bool trace, bool inner_loop, int inner_iterlim, double inner_tol, int alp_iterlim, double alp_tol, double alp_min, double alp_max);
RcppExport SEXP _MicrobiomeStat_bmdd_nlopt(SEXP WSEXP, SEXP typeSEXP, SEXP para_alp_initSEXP, SEXP para_pi_initSEXP, SEXP gam_initSEXP, SEXP iterlimSEXP, SEXP tolSEXP, SEXP traceSEXP, SEXP inner_loopSEXP, SEXP inner_iterlimSEXP, SEXP inner_tolSEXP, SEXP alp_iterlimSEXP, SEXP alp_tolSEXP, SEXP alp_minSEXP, SEXP alp_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type para_alp_init(para_alp_initSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type para_pi_init(para_pi_initSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type gam_init(gam_initSEXP);
    Rcpp::traits::input_parameter< int >::type iterlim(iterlimSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< bool >::type inner_loop(inner_loopSEXP);
    Rcpp::traits::input_parameter< int >::type inner_iterlim(inner_iterlimSEXP);
    Rcpp::traits::input_parameter< double >::type inner_tol(inner_tolSEXP);
    Rcpp::traits::input_parameter< int >::type alp_iterlim(alp_iterlimSEXP);
    Rcpp::traits::input_parameter< double >::type alp_tol(alp_tolSEXP);
    Rcpp::traits::input_parameter< double >::type alp_min(alp_minSEXP);
    Rcpp::traits::input_parameter< double >::type alp_max(alp_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(bmdd_nlopt(W, type, para_alp_init, para_pi_init, gam_init, iterlim, tol, trace, inner_loop, inner_iterlim, inner_tol, alp_iterlim, alp_tol, alp_min, alp_max));
    return rcpp_result_gen;
END_RCPP
}
// test_nlopt_available
bool test_nlopt_available();
RcppExport SEXP _MicrobiomeStat_test_nlopt_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_nlopt_available());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MicrobiomeStat_soft_c", (DL_FUNC) &_MicrobiomeStat_soft_c, 2},
    {"_MicrobiomeStat_ADMM_ab_cpp", (DL_FUNC) &_MicrobiomeStat_ADMM_ab_cpp, 5},
    {"_MicrobiomeStat_Soft_threshold_cpp", (DL_FUNC) &_MicrobiomeStat_Soft_threshold_cpp, 2},
    {"_MicrobiomeStat_bmdd_nlopt", (DL_FUNC) &_MicrobiomeStat_bmdd_nlopt, 15},
    {"_MicrobiomeStat_test_nlopt_available", (DL_FUNC) &_MicrobiomeStat_test_nlopt_available, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_MicrobiomeStat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
