# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_c <- function(a, lambda) {
    .Call(`_MicrobiomeStat_soft_c`, a, lambda)
}

ADMM_ab_cpp <- function(C, lambda, mu = 1, maxit = 100L, eps = 1e-5) {
    .Call(`_MicrobiomeStat_ADMM_ab_cpp`, C, lambda, mu, maxit, eps)
}

Soft_threshold_cpp <- function(C, lambda) {
    .Call(`_MicrobiomeStat_Soft_threshold_cpp`, C, lambda)
}

bmdd_nlopt <- function(W, type, para_alp_init = NULL, para_pi_init = NULL, gam_init = NULL, iterlim = 500L, tol = 1e-6, trace = FALSE, inner_loop = TRUE, inner_iterlim = 20L, inner_tol = 1e-6, alp_iterlim = 100L, alp_tol = 1e-6, alp_min = 1e-3, alp_max = 1e3) {
    .Call(`_MicrobiomeStat_bmdd_nlopt`, W, type, para_alp_init, para_pi_init, gam_init, iterlim, tol, trace, inner_loop, inner_iterlim, inner_tol, alp_iterlim, alp_tol, alp_min, alp_max)
}

test_nlopt_available <- function() {
    .Call(`_MicrobiomeStat_test_nlopt_available`)
}

